# Generated by Django 4.2.1 on 2023-06-27 04:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Form1', '0002_nhan_vien_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='thong_tin_nhan_vien',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
