# Generated by Django 4.2.1 on 2023-06-28 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Form1', '0003_thong_tin_nhan_vien_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thong_tin_nhan_vien',
            name='user',
        ),
    ]
